name: vitafit
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_settings: 5.1.1
  badges: 3.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: 4.15.9
  cloud_functions: 4.6.9
  country_code_picker: 3.0.0
  country_picker: 2.0.25
  device_info_plus: 9.1.1
  firebase_app_check: 0.2.1+18
  firebase_auth: 4.17.9
  firebase_core: 2.27.1
  firebase_database: 10.4.10
  firebase_dynamic_links: 5.4.18
  firebase_in_app_messaging: 0.7.4+18
  firebase_messaging: 14.7.20
  firebase_remote_config: 4.3.18
  firebase_storage: 11.6.10
  flutter_local_notifications: 17.0.0
  flutter_screenutil: 5.9.0
  flutter_spinkit: 5.2.0
  flutter_svg: 1.1.6
  google_sign_in_web: 0.12.4
  google_sign_in: 6.2.1
  http: 1.2.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  image_cropper: 5.0.1
  image_picker: 1.0.7
  intl: 0.18.1
  lottie: 3.1.0
  package_info_plus: 4.2.0
  permission_handler: 11.3.0
  provider: 6.1.2
  share_plus: 7.2.1
  shared_preferences: 2.2.2
  sign_in_with_apple: 6.1.0
  smooth_page_indicator: 1.1.0
  url_launcher: 6.2.5
  card_swiper: ^3.0.1
  iconly: ^1.0.1
  flutter_custom_clippers: ^2.1.0
  cupertino_icons: ^1.0.6
  appinio_animated_toggle_tab: ^1.0.3
  percent_indicator: ^4.2.3
  sweet_cookie_jar:
    git:
      url: https://github.com/OssMess/sweet-cookie-jar.git
      ref: 03f728e
  syncfusion_flutter_signaturepad: ^25.1.39
  rate_my_app: ^2.0.0
  cool_dropdown: ^2.1.0
  google_fonts: ^6.2.0
  photo_gallery: ^2.2.1
  flutter_image_compress: ^2.3.0
  intl_utils: ^2.8.7
  image_picker_platform_interface: ^2.10.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  flutter pub run change_app_package_name:main com.example.app
  change_app_package_name: 1.1.0
  # flutter pub run flutter_launcher_icons
  flutter_launcher_icons: 0.13.1
  flutter_lints: 2.0.3

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lotties/
    - assets/images/auth_images/
    - assets/images/auth_images/forgot-password/
    - assets/images/auth_images/tablet-login/
    - assets/coaches/
    - assets/icons/
    - assets/images/SALES DISCOUNT/
    - assets/images/other/
    - assets/images/home/
    - assets/images/OnBoarding/
    - assets/images/healthy product/
    - assets/images/shoes/
    - assets/images/favorite/
    - assets/images/all/
    - assets/images/brassiere/
    - assets/images/buttom/
    - assets/images/sport materials/
    - assets/images/suite/
    - assets/images/top/
   


   
  fonts:
    - family: AwesomeIconsLight
      fonts:
        - asset: assets/fonts/AwesomeIconsLight.ttf
    - family: AwesomeIconsRegular
      fonts:
        - asset: assets/fonts/AwesomeIconsRegular.ttf
    - family: AwesomeIconsSolid
      fonts:
        - asset: assets/fonts/AwesomeIconsSolid.ttf
    - family: AwesomeIconsBrands
      fonts:
        - asset: assets/fonts/AwesomeIconsBrands.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf      