// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIoop-eBSUcfdVqVbsbnGCXlPWd7seJQ',
    appId: '1:865528263704:android:ee36a391945b89705f7f6d',
    messagingSenderId: '865528263704',
    projectId: 'vitafit-369c1',
    storageBucket: 'vitafit-369c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxdryvqHjaq7JsfD1PmqgFyGpKnJEYvbg',
    appId: '1:865528263704:ios:9d9f15add72004615f7f6d',
    messagingSenderId: '865528263704',
    projectId: 'vitafit-369c1',
    storageBucket: 'vitafit-369c1.appspot.com',
    androidClientId: '865528263704-04bskorqgjq3qnekr3ekno1i1icc2vjn.apps.googleusercontent.com',
    iosClientId: '865528263704-l7qa5revnto0g1fe3hokjt7fcb0sie0j.apps.googleusercontent.com',
    iosBundleId: 'com.vitafit.app',
  );
}
