/// Flutter icons AwesomeIconsLight
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AwesomeIconsLight
///      fonts:
///       - asset: fonts/AwesomeIconsLight.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class AwesomeIconsLight {
  AwesomeIconsLight._();

  static const _kFontFam = 'AwesomeIconsLight';
  static const String? _kFontPkg = null;

  static const IconData address_card =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aperture =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_big_small =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_to_line =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_wide_short =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_from_bracket =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_rotate_left =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_rotate_right =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_short_wide =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_shopping =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars_sort =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_check =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_open =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_low =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_retro =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_shopping =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_column =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_info =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_question =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_user =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_x =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clapperboard_play =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_medical =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_rotate_left =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_sign =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_contract =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_signature =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_xmark =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_list =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_heart =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_polaroid_user =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_user =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData images =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData input_numeric =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_dot =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_keyhole_open =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_keyhole =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manage_search =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_minus =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_xmark =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_top =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_line =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podcast =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle_history =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle_vertical_history =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_nodes =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sparkles =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_info =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunglasses =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_1 =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbtack =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_fast =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_ramp_box =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_group =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_large =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_shield =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vest_patches =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_plus =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_xmark =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xmark =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
